"""init.

Revision ID: 171271b45a9e
Revises:
Create Date: 2026-05-17 10:34:53.875352

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '171271b45a9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=True),
        sa.Column('password_salt', sa.String(), nullable=True),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    )
    op.create_index(
        'user_email_uq_partial_idx',
        'user',
        ['email'],
        unique=True,
        postgresql_where=sa.text('deleted_at IS NULL'),
    )
    op.create_table(
        'session',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('ip_address', postgresql.INET(), nullable=True),
        sa.Column('user_agent', sa.String(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('refresh_token_hash', postgresql.BYTEA(), nullable=False),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'], ['user.id'], name=op.f('session_user_id_fkey'), ondelete='RESTRICT'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('session_pkey')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    op.drop_index(
        'user_email_uq_partial_idx',
        table_name='user',
        postgresql_where=sa.text('deleted_at IS NULL'),
    )
    op.drop_table('user')
    # ### end Alembic commands ###
